openapi: 3.0.0
info:
  description: "OpenAPI file that describes pytest-gui api"
  version: "1.0.0"
  title: "OpenAPI REST Article"

servers:
  - url: "/api"
    description: "API server"

paths:
  /discover:
    $ref: "./endpoints/actions/actions.yaml#/discover"
  /run:
    $ref: "./endpoints/actions/actions.yaml#/run"
  /stop:
    $ref: "./endpoints/actions/actions.yaml#/stop"
  /markers:
    $ref: "./endpoints/markers/markers.yaml#/markers"
  /status:
    $ref: "./endpoints/streams/streams.yaml#/status"
  /logs:
    $ref: "./endpoints/streams/streams.yaml#/logs"

components:
  schemas:
    Test:
      type: object
      properties:
        nodeid:
          type: string
        module:
          type: string
        file:
          type: string
        id:
          type: string
        markers:
          type: array
          items:
            $ref: "#/components/schemas/Marker"
      required:
        - nodeid
        - module
        - file
        - id
        - markers

    Marker:
      type: string
