swagger: "2.0"
info:
  description: Swagger file that describes pytest-gui api
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /discover:
    get:
      operationId: "discover.get"
      tags:
        - "Discover"
      summary: "The tests data structure supported by the server application"
      description: "Get the list of tests"
      responses:
        200:
          description: "Successfully got test list operation"
          schema:
            type: "array"
            items:
              properties:
                name:
                  type: "string"
                tests:
                  type: "array"
                  items:
                    properties:
                      name:
                        type: "string"
                      line:
                        type: "integer"
                      selected:
                        type: "boolean"
  /markers:
    get:
      operationId: "markers.get"
      tags:
        - "Markers"
      summary: "The test markers registered"
      description: "Get the list of markers"
      responses:
        200:
          description: "Successfully got marker list operation"
          schema:
            type: "array"
            items:
              properties:
                name:
                  type: "string"
                tests:
                  type: "array"
                  items:
                    properties:
                      name:
                        type: "string"
                      line:
                        type: "integer"
                      selected:
                        type: "boolean"
  /test:
    get:
      operationId: "test.get"
      tags:
        - "Tests"
      summary: "Get all tests"
      description: "Get the list of tests"
      responses:
        200:
          description: "Successfully got test list operation"
          schema:
            type: "array"
            items:
              properties:
                name:
                  type: "string"
                description:
                  type: "string"
  /select:
    post:
      operationId: "test.select"
      tags:
        - "Tests"
      summary: Selects a test.
      consumes:
        - application/json
      parameters:
        - in: body
          name: test
          description: The test to select.
          schema:
            type: object
            required:
              - name
              - module
              - selected
            properties:
              name:
                type: string
              module:
                type: string
              selected:
                type: boolean
      responses:
        201:
          description: Created
