swagger: "2.0"
info:
  description: Swagger file that describes pytest-gui api
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /discover:
    get:
      operationId: "discover.get"
      tags:
        - "Discover"
      summary: "The tests data structure supported by the server application"
      description: "Get the list of tests"
      responses:
        200:
          description: "Successful got test list operation"
          schema:
            type: "array"
            items:
              properties:
                parent:
                  type: "string"
                name:
                  type: "string"
                selected:
                  type: "boolean"
